title = "DevSecOps Lab Rules"

[[rules]]
description = "AWS Secret Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "Generic API Key"
regex = '''(?i)(api|token|secret|key)[-_]?(key)?\s*=\s*["']?[A-Za-z0-9_\-]{16,}'''
tags = ["generic"]
